/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.jumbledwords;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Example customization of dimensions originally defined in res/values/dimens.xml
         (such as screen margins) for screens with more than 820dp of available width. This
         would include 7" and 10" devices in landscape (~960dp and ~1280dp respectively).
    
         */
        public static final int activity_horizontal_margin=0x7f060000;
        public static final int activity_vertical_margin=0x7f060001;
    }
    public static final class drawable {
        public static final int a=0x7f020000;
        public static final int addf=0x7f020001;
        public static final int ar=0x7f020002;
        public static final int b=0x7f020003;
        public static final int blank=0x7f020004;
        public static final int br=0x7f020005;
        public static final int button_design=0x7f020006;
        public static final int c=0x7f020007;
        public static final int cr=0x7f020008;
        public static final int d=0x7f020009;
        public static final int download=0x7f02000a;
        public static final int dr=0x7f02000b;
        public static final int e=0x7f02000c;
        public static final int er=0x7f02000d;
        public static final int f=0x7f02000e;
        public static final int finalogo=0x7f02000f;
        public static final int fr=0x7f020010;
        public static final int g=0x7f020011;
        public static final int gr=0x7f020012;
        public static final int h=0x7f020013;
        public static final int hr=0x7f020014;
        public static final int i=0x7f020015;
        public static final int ic_launcher=0x7f020016;
        public static final int ir=0x7f020017;
        public static final int j=0x7f020018;
        public static final int jr=0x7f020019;
        public static final int k=0x7f02001a;
        public static final int kr=0x7f02001b;
        public static final int l=0x7f02001c;
        public static final int lout=0x7f02001d;
        public static final int lr=0x7f02001e;
        public static final int m=0x7f02001f;
        public static final int mr=0x7f020020;
        public static final int n=0x7f020021;
        public static final int newp=0x7f020022;
        public static final int nr=0x7f020023;
        public static final int o=0x7f020024;
        public static final int or=0x7f020025;
        public static final int p=0x7f020026;
        public static final int pr=0x7f020027;
        public static final int q=0x7f020028;
        public static final int qr=0x7f020029;
        public static final int r=0x7f02002a;
        public static final int red=0x7f02002b;
        public static final int rr=0x7f02002c;
        public static final int s=0x7f02002d;
        public static final int sr=0x7f02002e;
        public static final int t=0x7f02002f;
        public static final int tr=0x7f020030;
        public static final int u=0x7f020031;
        public static final int ur=0x7f020032;
        public static final int v=0x7f020033;
        public static final int vr=0x7f020034;
        public static final int w=0x7f020035;
        public static final int wr=0x7f020036;
        public static final int x=0x7f020037;
        public static final int xr=0x7f020038;
        public static final int y=0x7f020039;
        public static final int yr=0x7f02003a;
        public static final int z=0x7f02003b;
        public static final int zr=0x7f02003c;
    }
    public static final class id {
        public static final int action_settings=0x7f0a0034;
        public static final int b1=0x7f0a0011;
        public static final int dr_b1=0x7f0a0001;
        public static final int dr_b2=0x7f0a0003;
        public static final int dr_b3=0x7f0a0002;
        public static final int dr_et1=0x7f0a0000;
        public static final int g_b1=0x7f0a0005;
        public static final int g_tv1=0x7f0a0004;
        public static final int ib1=0x7f0a0023;
        public static final int ib2=0x7f0a0021;
        public static final int ib3=0x7f0a0022;
        public static final int ib4=0x7f0a0024;
        public static final int ib5=0x7f0a0025;
        public static final int imageView1=0x7f0a000e;
        public static final int imageView2=0x7f0a000f;
        public static final int ins_b1=0x7f0a0008;
        public static final int ins_tv=0x7f0a0007;
        public static final int linearLayout1=0x7f0a0009;
        public static final int t5_b1=0x7f0a0019;
        public static final int t5_b2=0x7f0a001a;
        public static final int t5_b3=0x7f0a001b;
        public static final int t5_b4=0x7f0a001c;
        public static final int t5_b5=0x7f0a001d;
        public static final int t5_bb=0x7f0a001f;
        public static final int t5_bs=0x7f0a0020;
        public static final int t5_tv=0x7f0a001e;
        public static final int t7_b1=0x7f0a002a;
        public static final int t7_b2=0x7f0a002b;
        public static final int t7_b3=0x7f0a002c;
        public static final int t7_b4=0x7f0a002d;
        public static final int t7_b5=0x7f0a002e;
        public static final int t7_b6=0x7f0a002f;
        public static final int t7_b7=0x7f0a0030;
        public static final int t7_bb=0x7f0a0032;
        public static final int t7_bs=0x7f0a0033;
        public static final int t7_tv1=0x7f0a0031;
        public static final int t_b1=0x7f0a0012;
        public static final int t_b2=0x7f0a0013;
        public static final int t_b3=0x7f0a0014;
        public static final int t_b4=0x7f0a0015;
        public static final int t_bb=0x7f0a0017;
        public static final int t_bs=0x7f0a0018;
        public static final int t_tv1=0x7f0a0016;
        public static final int textView1=0x7f0a0006;
        public static final int textView2=0x7f0a000a;
        public static final int textView3=0x7f0a000b;
        public static final int textView4=0x7f0a000c;
        public static final int textView5=0x7f0a000d;
        public static final int textView6=0x7f0a0010;
        public static final int w_b1=0x7f0a0029;
        public static final int w_b2=0x7f0a0026;
        public static final int w_b3=0x7f0a0027;
        public static final int w_b4=0x7f0a0028;
    }
    public static final class layout {
        public static final int activity_demo_run=0x7f030000;
        public static final int activity_greeting=0x7f030001;
        public static final int activity_home_screen=0x7f030002;
        public static final int activity_instructions=0x7f030003;
        public static final int activity_page2=0x7f030004;
        public static final int activity_three=0x7f030005;
        public static final int activity_trial=0x7f030006;
        public static final int activity_trial_five=0x7f030007;
        public static final int activity_two=0x7f030008;
        public static final int activity_welcomepage=0x7f030009;
        public static final int activity_wifi_demo=0x7f03000a;
        public static final int activity_word_trail7=0x7f03000b;
    }
    public static final class menu {
        public static final int demo_run=0x7f090000;
        public static final int greeting=0x7f090001;
        public static final int home_screen=0x7f090002;
        public static final int instructions=0x7f090003;
        public static final int page2=0x7f090004;
        public static final int three=0x7f090005;
        public static final int trial=0x7f090006;
        public static final int trial_five=0x7f090007;
        public static final int two=0x7f090008;
        public static final int welcomepage=0x7f090009;
        public static final int wifi_demo=0x7f09000a;
        public static final int word_trail7=0x7f09000b;
    }
    public static final class raw {
        public static final int backaudio=0x7f050000;
        public static final int bog=0x7f050001;
        public static final int instrumental=0x7f050002;
        public static final int puzzlemusic=0x7f050003;
    }
    public static final class string {
        public static final int action_settings=0x7f070002;
        public static final int app_name=0x7f070000;
        public static final int hello_world=0x7f070001;
        public static final int title_activity_demo_run=0x7f070008;
        public static final int title_activity_greeting=0x7f07000c;
        public static final int title_activity_home_screen=0x7f070009;
        public static final int title_activity_instructions=0x7f07000d;
        public static final int title_activity_page2=0x7f070003;
        public static final int title_activity_three=0x7f070006;
        public static final int title_activity_trial=0x7f070004;
        public static final int title_activity_trial_five=0x7f07000b;
        public static final int title_activity_two=0x7f070005;
        public static final int title_activity_wifi_demo=0x7f07000a;
        public static final int title_activity_word_trail7=0x7f070007;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f080000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f080001;
    }
    public static final class xml {
        public static final int settings=0x7f040000;
    }
}
